### PR TITLE
raspinfo: Add some audio info to debug log

### PR DESCRIPTION
**Pull request by popcornmix**

### CODE REVIEW

**Comment by popcornmix** [comment]
@6by9 @pelwell @hiassoft

Can you think of anything else that useful for debugging (lack of) audio issues?

**Comment by 6by9** [comment]
I can't claim to be an expert on all things audio, but the commands added look reasonable.

**Comment by pelwell** [comment]
I can't think of anything else. The aplay output would include the name of any audio HAT.

**Comment by HiassofT** [comment]
I think that's fine, too. Anything else like dumping mixer controls / contents would be too noisy

**Comment by popcornmix** [comment]
Thanks - wasn't sure if I was missing anything useful.

**Pull request merged**
