### PR TITLE
vclog: Also try /dev/vc-mem for DMA copy

### PR DESCRIPTION
**Pull request by pelwell**
Allow for the fact that the dma_memcpy support may be provided by the vc_mem driver.

### CODE REVIEW

**Comment by pelwell** [comment]
https://github.com/raspberrypi/linux/pull/5651 is the corresponding kernel change.

**Comment by timg236** [comment]
Does this work on Pi5 if there are no framebuffers? i.e. headless with max_framebuffers=0 ?

**Comment by pelwell** [comment]
This change (along with the kernel patch) is designed specifically for the no framebuffer case. However, Pi 5 is a bit special:
* It has no memory hole, so it as no need for the DMA support.
* The DMA controller's view of the world is different, so it doesn't need the high address alias bits setting.

The result is that the log appears, but at the cost of a logged kernel error:
```
[   30.137022] vc_mem_copy: invalid memory access 3ff16000 (fdb00000-ffc00000)
```
I think this patch in itself is fine, but the vc-mem driver should be modified to fail (or just memcpy) on non-2710 platforms.

**Comment by timg236** [comment]
Yes, that makes sense.

**Comment by pelwell** [comment]
On that basis I'm going to merge this and revisit the vc_mem patch.

**Comment by popcornmix** [comment]
@XECDesign would be good to get this into RPiOS image soon.
Currently vclog is broken on Pi2/Pi3.
We also need a kernel bump, but it's safe to update this first.

**Comment by XECDesign** [comment]
Should be available in apt now

**Pull request merged**
